# Generated by Django 3.0.2 on 2020-02-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
